# Generated by Django 3.2.5 on 2022-02-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(default='first-name', max_length=90)),
                ('last_name', models.CharField(default='last-name', max_length=90)),
                ('username', models.CharField(default='username', max_length=90)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_picture', models.ImageField(default='user.svg', upload_to='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
